# Generated by Django 3.0.2 on 2020-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bosyu_join_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosyu',
            name='venue',
            field=models.CharField(default=999, max_length=50),
            preserve_default=False,
        ),
    ]
