# Generated by Django 3.0.2 on 2020-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_bosyu_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosyu',
            name='status',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
