# Generated by Django 3.0.2 on 2020-02-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bosyu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosyu',
            name='venue_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
