# Generated by Django 3.0.2 on 2020-02-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_bosyu_venue_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosyu',
            name='bosyu_limit',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bosyu',
            name='venue_datetime',
            field=models.DateTimeField(),
        ),
    ]
