# Generated by Django 3.0.2 on 2020-02-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200202_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bosyu',
            options={'ordering': ['-bosyu_limit']},
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=999, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='join',
            name='bosyu_seq',
            field=models.ForeignKey(db_column='bosyu_seq', on_delete=django.db.models.deletion.CASCADE, to='blog.Bosyu'),
        ),
    ]
