# Generated by Django 3.0.2 on 2020-02-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200202_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosyu',
            name='post_user_nm',
            field=models.CharField(default=22222222222222, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join',
            name='join_user_nm',
            field=models.CharField(default=2222222222222222222222222, max_length=50),
            preserve_default=False,
        ),
    ]
