# Generated by Django 3.0.2 on 2020-02-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200204_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosyu',
            name='post_user_nm',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='join',
            name='join_user_nm',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
