# Generated by Django 3.0.3 on 2020-03-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bosyu',
            fields=[
                ('bosyu_seq', models.AutoField(primary_key=True, serialize=False)),
                ('bosyu_kbn', models.CharField(choices=[('1', '勉強会'), ('2', '交流会'), ('9', 'その他')], max_length=1)),
                ('bosyu_limit', models.DateTimeField()),
                ('venue', models.CharField(max_length=50)),
                ('venue_datetime', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('main_text', models.TextField(max_length=1000)),
                ('bosyu_people_cnt', models.IntegerField()),
                ('bosyu_peple_kbn', models.CharField(choices=[('1', '人以上'), ('2', '人以下'), ('9', '人')], max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('post_datetime', models.DateTimeField(auto_now=True)),
                ('post_user_id', models.CharField(max_length=8)),
                ('post_user_nm', models.TextField(max_length=50)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('update_user_id', models.CharField(max_length=8)),
                ('delete_flg', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['-bosyu_limit'],
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('join_seq', models.AutoField(primary_key=True, serialize=False)),
                ('join_user_id', models.CharField(max_length=8)),
                ('join_user_nm', models.TextField(max_length=50)),
                ('join_app_datetime', models.DateTimeField(auto_now=True)),
                ('delete_flg', models.CharField(max_length=1)),
                ('bosyu_seq', models.ForeignKey(db_column='bosyu_seq', on_delete=django.db.models.deletion.CASCADE, to='curaoff.Bosyu')),
            ],
        ),
    ]
